version: '3.8'

services:
  weather-service:
    build: .
    container_name: weather-microservice
    ports:
      - "3000:3000"
    environment:
      - SERVER_ADDRESS=:3000
      - READ_TIMEOUT=10
      - WRITE_TIMEOUT=10
      - IDLE_TIMEOUT=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
